export type CommunityIdeaCategory =
	| "AI"
	| "Crypto"
	| "Health"
	| "Industry"
	| "Macro"
	| "People"
	| "Tech";

export interface CommunityIdeaHolding {
	symbol: string;
	name: string;
	weightBps: number;
	reason?: string;
}

export interface CommunityIdea {
	id: string;
	title: string;
	description: string;
	category: CommunityIdeaCategory;
	anchorSymbols: string[];
	historicalReturn1Y?: number;
	holdings?: CommunityIdeaHolding[];
}

export const COMMUNITY_IDEAS: CommunityIdea[] = [
	{
		id: "mag7-spacex",
		title: "Big Tech + SpaceX",
		description: "Mega-cap technology paired with SpaceX exposure.",
		category: "Tech",
		anchorSymbols: ["NVDAx", "MSFTx", "SPACEX"],
		holdings: [
			{ symbol: "NVDAx", name: "NVIDIA", weightBps: 1250 },
			{ symbol: "TSLAx", name: "Tesla", weightBps: 1250 },
			{ symbol: "MSFTx", name: "Microsoft", weightBps: 1250 },
			{ symbol: "AAPLx", name: "Apple", weightBps: 1250 },
			{ symbol: "AMZNx", name: "Amazon", weightBps: 1250 },
			{ symbol: "GOOGLx", name: "Alphabet", weightBps: 1250 },
			{ symbol: "METAx", name: "Meta", weightBps: 1250 },
			{ symbol: "SPACEX", name: "SpaceX", weightBps: 1250 },
		],
	},
	{
		id: "nancy-pelosi",
		title: "Nancy Pelosi",
		description:
			"A portfolio inspired by publicly disclosed US politician trades.",
		category: "People",
		anchorSymbols: ["NVDAx", "AMZNx", "GOOGLx"],
		historicalReturn1Y: 61.11,
		holdings: [
			{ symbol: "PANWx", name: "Palo Alto Networks", weightBps: 1417 },
			{ symbol: "INTCx", name: "Intel", weightBps: 1165 },
			{ symbol: "AVGOx", name: "Broadcom", weightBps: 1075 },
			{ symbol: "GOOGLx", name: "Alphabet", weightBps: 1071 },
			{ symbol: "CRWDx", name: "CrowdStrike", weightBps: 1109 },
			{ symbol: "UBERx", name: "Uber", weightBps: 970 },
			{ symbol: "AMZNx", name: "Amazon", weightBps: 898 },
			{ symbol: "VSTx", name: "Vistra", weightBps: 784 },
			{ symbol: "NVDAx", name: "NVIDIA", weightBps: 591 },
			{ symbol: "MSFTx", name: "Microsoft", weightBps: 517 },
			{ symbol: "AAPLx", name: "Apple", weightBps: 403 },
		],
	},
	{
		id: "warren-buffett",
		title: "Warren Buffett",
		description: "Quality companies inspired by Berkshire Hathaway holdings.",
		category: "People",
		anchorSymbols: ["BRK.Bx", "KOx", "AAPLx"],
		historicalReturn1Y: 30.71,
		holdings: [
			{ symbol: "AAPLx", name: "Apple", weightBps: 3493 },
			{ symbol: "AXPx", name: "American Express", weightBps: 1674 },
			{ symbol: "BACx", name: "Bank of America", weightBps: 1401 },
			{ symbol: "KOx", name: "Coca-Cola", weightBps: 1171 },
			{ symbol: "GOOGLx", name: "Alphabet", weightBps: 796 },
			{ symbol: "CVXx", name: "Chevron", weightBps: 751 },
			{ symbol: "OXYx", name: "Occidental Petroleum", weightBps: 612 },
			{ symbol: "VRSNx", name: "VeriSign", weightBps: 102 },
		],
	},
	{
		id: "leopold-aschenbrenner",
		title: "Leopold Aschenbrenner",
		description:
			"AI infrastructure, strategic compute and industrial capacity.",
		category: "People",
		anchorSymbols: ["NVDAx", "ASMLx", "TSMx"],
		historicalReturn1Y: 88.52,
		holdings: [
			{ symbol: "MUx", name: "Micron Technology", weightBps: 2364 },
			{ symbol: "SNDKx", name: "SanDisk", weightBps: 2241 },
			{ symbol: "BEx", name: "Bloom Energy", weightBps: 1201 },
			{ symbol: "TSMx", name: "Taiwan Semiconductor", weightBps: 711 },
			{ symbol: "NBISx", name: "Nebius", weightBps: 642 },
			{ symbol: "CRWVx", name: "CoreWeave", weightBps: 389 },
			{ symbol: "KEELx", name: "Keel Infrastructure", weightBps: 383 },
			{ symbol: "CORZx", name: "Core Scientific", weightBps: 337 },
			{ symbol: "WYFIx", name: "WhiteFiber", weightBps: 304 },
			{ symbol: "BTDRx", name: "Bitdeer Technologies", weightBps: 312 },
			{ symbol: "HIVEx", name: "HIVE Digital", weightBps: 307 },
			{ symbol: "STMx", name: "STMicroelectronics", weightBps: 316 },
			{ symbol: "APLDx", name: "Applied Digital", weightBps: 244 },
			{ symbol: "RIOTx", name: "Riot Platforms", weightBps: 249 },
		],
	},
	{
		id: "cathie-wood",
		title: "Cathie Wood",
		description: "High-conviction exposure to disruptive innovation companies.",
		category: "People",
		anchorSymbols: ["TSLAx", "COINx", "ROKUx"],
		historicalReturn1Y: 100.94,
		holdings: [
			{ symbol: "TSLAx", name: "Tesla", weightBps: 1444 },
			{ symbol: "AMDx", name: "AMD", weightBps: 1022 },
			{ symbol: "SPACEX", name: "SpaceX", weightBps: 987 },
			{ symbol: "HOODx", name: "Robinhood", weightBps: 814 },
			{ symbol: "SHOPx", name: "Shopify", weightBps: 842 },
			{ symbol: "PLTRx", name: "Palantir", weightBps: 802 },
			{ symbol: "COINx", name: "Coinbase", weightBps: 705 },
			{ symbol: "CRCLx", name: "Circle", weightBps: 695 },
			{ symbol: "AMZNx", name: "Amazon", weightBps: 613 },
			{ symbol: "GOOGLx", name: "Alphabet", weightBps: 557 },
			{ symbol: "NVDAx", name: "NVIDIA", weightBps: 523 },
			{ symbol: "RKLBx", name: "Rocket Lab", weightBps: 411 },
			{ symbol: "TERx", name: "Teradyne", weightBps: 365 },
			{ symbol: "ACHRx", name: "Archer Aviation", weightBps: 220 },
		],
	},
	{
		id: "mag-seven",
		title: "The Mag Seven",
		description:
			"The largest US technology platforms in one concentrated theme.",
		category: "Tech",
		anchorSymbols: ["AAPLx", "MSFTx", "NVDAx"],
		historicalReturn1Y: 19.87,
		holdings: [
			{ symbol: "NVDAx", name: "NVIDIA", weightBps: 1429 },
			{ symbol: "TSLAx", name: "Tesla", weightBps: 1429 },
			{ symbol: "MSFTx", name: "Microsoft", weightBps: 1429 },
			{ symbol: "AAPLx", name: "Apple", weightBps: 1429 },
			{ symbol: "AMZNx", name: "Amazon", weightBps: 1428 },
			{ symbol: "GOOGLx", name: "Alphabet", weightBps: 1428 },
			{ symbol: "METAx", name: "Meta", weightBps: 1428 },
		],
	},
	{
		id: "hard-money",
		title: "Gold, Bitcoin & Precious Metals",
		description:
			"Scarce monetary assets designed for currency-debasement scenarios.",
		category: "Macro",
		anchorSymbols: ["BTC", "GLDx", "SLVx"],
		historicalReturn1Y: 40.14,
		holdings: [
			{ symbol: "GLDx", name: "SPDR Gold Shares", weightBps: 3600 },
			{ symbol: "NEMx", name: "Newmont", weightBps: 1600 },
			{ symbol: "SLVx", name: "iShares Silver Trust", weightBps: 1600 },
			{ symbol: "IBITx", name: "iShares Bitcoin Trust", weightBps: 1600 },
			{ symbol: "AGx", name: "First Majestic Silver", weightBps: 800 },
			{ symbol: "PPLTx", name: "Physical Platinum Shares", weightBps: 800 },
		],
	},
	{
		id: "quantum-bet",
		title: "Quantum Computing",
		description: "Public companies building quantum hardware and software.",
		category: "Tech",
		anchorSymbols: ["IONQx", "RGTIx", "QBTSx"],
		historicalReturn1Y: 19.63,
		holdings: [
			{ symbol: "IBMx", name: "IBM", weightBps: 1900 },
			{ symbol: "NVDAx", name: "NVIDIA", weightBps: 1500 },
			{ symbol: "GOOGLx", name: "Alphabet", weightBps: 1500 },
			{ symbol: "IONQx", name: "IonQ", weightBps: 1300 },
			{ symbol: "RGTIx", name: "Rigetti Computing", weightBps: 1100 },
			{ symbol: "QBTSx", name: "D-Wave Quantum", weightBps: 1100 },
			{ symbol: "QUBTx", name: "Quantum Computing", weightBps: 900 },
			{ symbol: "ARQQx", name: "Arqit Quantum", weightBps: 700 },
		],
	},
	{
		id: "energy-infra",
		title: "Energy Infra",
		description:
			"Energy producers and infrastructure supporting rising power demand.",
		category: "Industry",
		anchorSymbols: ["XOMx", "CVXx", "GEVx"],
		historicalReturn1Y: 42.36,
		holdings: [
			{ symbol: "NEEx", name: "NextEra Energy", weightBps: 2200 },
			{ symbol: "GEVx", name: "GE Vernova", weightBps: 1800 },
			{ symbol: "ETNx", name: "Eaton", weightBps: 1300 },
			{ symbol: "FLNCx", name: "Fluence Energy", weightBps: 1100 },
			{ symbol: "ENPHx", name: "Enphase Energy", weightBps: 1000 },
			{ symbol: "SOx", name: "Southern", weightBps: 900 },
			{ symbol: "PWRx", name: "Quanta Services", weightBps: 900 },
			{ symbol: "MTZx", name: "MasTec", weightBps: 800 },
		],
	},
	{
		id: "pure-silicon",
		title: "Semiconductor Stocks",
		description:
			"Semiconductor designers, foundries and fabrication equipment.",
		category: "Tech",
		anchorSymbols: ["NVDAx", "TSMx", "ASMLx"],
		historicalReturn1Y: 137.44,
		holdings: [
			{ symbol: "NVDAx", name: "NVIDIA", weightBps: 2000 },
			{ symbol: "TSMx", name: "Taiwan Semiconductor", weightBps: 1300 },
			{ symbol: "AVGOx", name: "Broadcom", weightBps: 1000 },
			{ symbol: "AMDx", name: "AMD", weightBps: 1000 },
			{ symbol: "ASMLx", name: "ASML", weightBps: 1000 },
			{ symbol: "AMATx", name: "Applied Materials", weightBps: 700 },
			{ symbol: "QCOMx", name: "Qualcomm", weightBps: 700 },
			{ symbol: "INTCx", name: "Intel", weightBps: 600 },
			{ symbol: "MRVLx", name: "Marvell Technology", weightBps: 600 },
			{ symbol: "MUx", name: "Micron Technology", weightBps: 1100 },
		],
	},
	{
		id: "neo-finance",
		title: "Neo Finance",
		description: "Digital brokers, exchanges and modern financial platforms.",
		category: "Macro",
		anchorSymbols: ["COINx", "HOODx", "SOFIx"],
		historicalReturn1Y: -5.31,
		holdings: [
			{ symbol: "COINx", name: "Coinbase", weightBps: 1400 },
			{ symbol: "HOODx", name: "Robinhood", weightBps: 1200 },
			{ symbol: "Vx", name: "Visa", weightBps: 1200 },
			{ symbol: "SOFIx", name: "SoFi", weightBps: 1100 },
			{ symbol: "MAx", name: "Mastercard", weightBps: 1100 },
			{ symbol: "XYZx", name: "Block", weightBps: 1000 },
			{ symbol: "PYPLx", name: "PayPal", weightBps: 800 },
			{ symbol: "AXPx", name: "American Express", weightBps: 700 },
			{ symbol: "SCHWx", name: "Charles Schwab", weightBps: 700 },
			{ symbol: "CRCLx", name: "Circle", weightBps: 800 },
		],
	},
	{
		id: "compute-grab",
		title: "AI Data Centers & Computing",
		description: "Accelerators, networking and data-center compute capacity.",
		category: "AI",
		anchorSymbols: ["NVDAx", "AMDx", "AVGOx"],
		historicalReturn1Y: 22.59,
		holdings: [
			{ symbol: "KEELx", name: "Keel Infrastructure", weightBps: 1500 },
			{ symbol: "IRENx", name: "IREN", weightBps: 1400 },
			{ symbol: "CORZx", name: "Core Scientific", weightBps: 1200 },
			{ symbol: "CRWVx", name: "CoreWeave", weightBps: 1100 },
			{ symbol: "APLDx", name: "Applied Digital", weightBps: 1000 },
			{ symbol: "CEGx", name: "Constellation Energy", weightBps: 1000 },
			{ symbol: "CIFRx", name: "Cipher Mining", weightBps: 1000 },
			{ symbol: "WULFx", name: "TeraWulf", weightBps: 900 },
			{ symbol: "NBISx", name: "Nebius", weightBps: 900 },
		],
	},
	{
		id: "ai-full-stack",
		title: "AI Chips, Cloud & Software",
		description:
			"AI exposure from chips and cloud to applications and distribution.",
		category: "AI",
		anchorSymbols: ["NVDAx", "MSFTx", "GOOGLx"],
		historicalReturn1Y: 40.11,
		holdings: [
			{ symbol: "NVDAx", name: "NVIDIA", weightBps: 1400 },
			{ symbol: "TSMx", name: "Taiwan Semiconductor", weightBps: 1000 },
			{ symbol: "AVGOx", name: "Broadcom", weightBps: 900 },
			{ symbol: "CEGx", name: "Constellation Energy", weightBps: 700 },
			{ symbol: "GEVx", name: "GE Vernova", weightBps: 700 },
			{ symbol: "NBISx", name: "Nebius", weightBps: 600 },
			{ symbol: "VRTx", name: "Vertiv", weightBps: 700 },
			{ symbol: "PLTRx", name: "Palantir", weightBps: 800 },
			{ symbol: "SMCIx", name: "Super Micro Computer", weightBps: 600 },
			{ symbol: "ANETx", name: "Arista Networks", weightBps: 700 },
			{ symbol: "ORCLx", name: "Oracle", weightBps: 700 },
			{ symbol: "CRWVx", name: "CoreWeave", weightBps: 600 },
			{ symbol: "VSTx", name: "Vistra", weightBps: 600 },
		],
	},
	{
		id: "defense-trade",
		title: "The Defense Trade",
		description:
			"Defense, aerospace and security companies tied to public spending.",
		category: "Industry",
		anchorSymbols: ["LMTx", "NOCx", "RTXx"],
		historicalReturn1Y: 19.03,
		holdings: [
			{ symbol: "RTXx", name: "RTX", weightBps: 1700 },
			{ symbol: "LMTx", name: "Lockheed Martin", weightBps: 1300 },
			{ symbol: "PLTRx", name: "Palantir", weightBps: 1200 },
			{ symbol: "GDx", name: "General Dynamics", weightBps: 1100 },
			{ symbol: "NOCx", name: "Northrop Grumman", weightBps: 1100 },
			{ symbol: "BAx", name: "Boeing", weightBps: 1000 },
			{ symbol: "GEx", name: "General Electric", weightBps: 900 },
			{ symbol: "BBAIx", name: "BigBear.ai", weightBps: 900 },
			{ symbol: "RKLBx", name: "Rocket Lab", weightBps: 800 },
		],
	},
	{
		id: "digital-fortress",
		title: "Digital Fortress",
		description:
			"Cybersecurity leaders protecting cloud, identity and internet infrastructure.",
		category: "Tech",
		anchorSymbols: ["CRWDx", "PANWx", "NETx"],
		historicalReturn1Y: 63.01,
		holdings: [
			{ symbol: "CRWDx", name: "CrowdStrike", weightBps: 2300 },
			{ symbol: "PANWx", name: "Palo Alto Networks", weightBps: 2100 },
			{ symbol: "NETx", name: "Cloudflare", weightBps: 1500 },
			{ symbol: "MSFTx", name: "Microsoft", weightBps: 1500 },
			{ symbol: "CSCOx", name: "Cisco", weightBps: 1400 },
			{ symbol: "VRSNx", name: "VeriSign", weightBps: 1200 },
		],
	},
	{
		id: "black-gold",
		title: "Black Gold",
		description:
			"Oil producers positioned for constrained global energy supply.",
		category: "Industry",
		anchorSymbols: ["XOMx", "CVXx", "OXYx"],
		historicalReturn1Y: 35.2,
		holdings: [
			{ symbol: "XOMx", name: "Exxon Mobil", weightBps: 2300 },
			{ symbol: "CVXx", name: "Chevron", weightBps: 1700 },
			{ symbol: "COPx", name: "ConocoPhillips", weightBps: 1400 },
			{ symbol: "OXYx", name: "Occidental Petroleum", weightBps: 1200 },
			{ symbol: "SLBx", name: "SLB", weightBps: 1000 },
			{ symbol: "WMBx", name: "Williams", weightBps: 900 },
			{ symbol: "EQTx", name: "EQT", weightBps: 800 },
			{ symbol: "HALx", name: "Halliburton", weightBps: 700 },
		],
	},
	{
		id: "space-race",
		title: "The Space Race",
		description:
			"Launch, satellite and aerospace companies commercializing orbit.",
		category: "Industry",
		anchorSymbols: ["TSLAx", "RKLBx", "LMTx"],
		historicalReturn1Y: 185.76,
		holdings: [
			{ symbol: "RKLBx", name: "Rocket Lab", weightBps: 1900 },
			{ symbol: "SPACEX", name: "SpaceX", weightBps: 1600 },
			{ symbol: "ASTSx", name: "AST SpaceMobile", weightBps: 1500 },
			{ symbol: "RDWx", name: "Redwire", weightBps: 1100 },
			{ symbol: "LUNRx", name: "Intuitive Machines", weightBps: 1000 },
			{ symbol: "IRDMx", name: "Iridium Communications", weightBps: 800 },
			{ symbol: "PLx", name: "Planet Labs", weightBps: 800 },
			{ symbol: "BAx", name: "Boeing", weightBps: 700 },
			{ symbol: "NOCx", name: "Northrop Grumman", weightBps: 600 },
		],
	},
	{
		id: "mine-future",
		title: "Minerals & Mining",
		description:
			"Critical-mineral miners supporting electrification, defense and advanced manufacturing.",
		category: "Industry",
		anchorSymbols: ["MPx", "FCXx", "USARx"],
		historicalReturn1Y: 50.95,
		holdings: [
			{ symbol: "MPx", name: "MP Materials", weightBps: 2000 },
			{ symbol: "FCXx", name: "Freeport-McMoRan", weightBps: 1700 },
			{ symbol: "USARx", name: "USA Rare Earth", weightBps: 1300 },
			{ symbol: "ALBx", name: "Albemarle", weightBps: 1200 },
			{ symbol: "NEMx", name: "Newmont", weightBps: 1000 },
			{ symbol: "SCCOx", name: "Southern Copper", weightBps: 1000 },
			{ symbol: "CLFx", name: "Cleveland-Cliffs", weightBps: 900 },
			{ symbol: "UECx", name: "Uranium Energy", weightBps: 900 },
		],
	},
	{
		id: "going-nuclear",
		title: "Nuclear Energy & Uranium",
		description:
			"Uranium, reactors and power producers exposed to nuclear demand.",
		category: "Industry",
		anchorSymbols: ["CCJx", "CEGx", "OKLOx"],
		historicalReturn1Y: -11.96,
		holdings: [
			{ symbol: "CEGx", name: "Constellation Energy", weightBps: 1600 },
			{ symbol: "CCJx", name: "Cameco", weightBps: 1500 },
			{ symbol: "SMRx", name: "NuScale Power", weightBps: 1200 },
			{ symbol: "OKLOx", name: "Oklo", weightBps: 1100 },
			{ symbol: "VSTx", name: "Vistra", weightBps: 1000 },
			{ symbol: "TLNx", name: "Talen Energy", weightBps: 900 },
			{ symbol: "UECx", name: "Uranium Energy", weightBps: 800 },
			{ symbol: "NNEx", name: "NANO Nuclear Energy", weightBps: 700 },
			{ symbol: "DNNx", name: "Denison Mines", weightBps: 600 },
			{ symbol: "UUUUx", name: "Energy Fuels", weightBps: 600 },
		],
	},
	{
		id: "consumer-brands",
		title: "Consumer Brands",
		description:
			"Global consumer franchises with durable distribution and demand.",
		category: "Macro",
		anchorSymbols: ["PGx", "KOx", "NKEx"],
		historicalReturn1Y: -8.11,
		holdings: [
			{ symbol: "NFLXx", name: "Netflix", weightBps: 1500 },
			{ symbol: "WMTx", name: "Walmart", weightBps: 1300 },
			{ symbol: "COSTx", name: "Costco", weightBps: 1100 },
			{ symbol: "MCDx", name: "McDonald's", weightBps: 1000 },
			{ symbol: "KOx", name: "Coca-Cola", weightBps: 900 },
			{ symbol: "NKEx", name: "Nike", weightBps: 800 },
			{ symbol: "DISx", name: "Disney", weightBps: 800 },
			{ symbol: "PEPx", name: "PepsiCo", weightBps: 800 },
			{ symbol: "SBUXx", name: "Starbucks", weightBps: 700 },
			{ symbol: "HDx", name: "Home Depot", weightBps: 600 },
			{ symbol: "CMGx", name: "Chipotle", weightBps: 500 },
		],
	},
	{
		id: "modern-medicine",
		title: "Pharma & Healthcare",
		description:
			"Drugmakers and healthcare leaders driving the next treatment cycle.",
		category: "Health",
		anchorSymbols: ["LLYx", "NVOx", "UNHx"],
		historicalReturn1Y: 26.99,
		holdings: [
			{ symbol: "LLYx", name: "Eli Lilly", weightBps: 2400 },
			{ symbol: "NVOx", name: "Novo Nordisk", weightBps: 1200 },
			{ symbol: "ABBVx", name: "AbbVie", weightBps: 1100 },
			{ symbol: "MRKx", name: "Merck", weightBps: 900 },
			{ symbol: "PFEx", name: "Pfizer", weightBps: 800 },
			{ symbol: "ABTx", name: "Abbott", weightBps: 800 },
			{ symbol: "ISRGx", name: "Intuitive Surgical", weightBps: 700 },
			{ symbol: "REGNx", name: "Regeneron", weightBps: 700 },
			{ symbol: "VRTXx", name: "Vertex Pharmaceuticals", weightBps: 700 },
			{ symbol: "UNHx", name: "UnitedHealth", weightBps: 700 },
		],
	},
	{
		id: "road-ahead",
		title: "Electric & Autonomous Vehicles",
		description:
			"Electric vehicles, autonomy and the platforms reshaping mobility.",
		category: "Industry",
		anchorSymbols: ["TSLAx", "UBERx", "GMx"],
		historicalReturn1Y: -0.79,
		holdings: [
			{ symbol: "TSLAx", name: "Tesla", weightBps: 2400 },
			{ symbol: "UBERx", name: "Uber", weightBps: 1500 },
			{ symbol: "RIVNx", name: "Rivian", weightBps: 1300 },
			{ symbol: "Fx", name: "Ford", weightBps: 1000 },
			{ symbol: "NIOx", name: "NIO", weightBps: 900 },
			{ symbol: "AURx", name: "Aurora Innovation", weightBps: 800 },
			{ symbol: "TMx", name: "Toyota", weightBps: 700 },
			{ symbol: "LIx", name: "Li Auto", weightBps: 700 },
			{ symbol: "MBLYx", name: "Mobileye", weightBps: 700 },
		],
	},
	{
		id: "tokenized-treasury-yield",
		title: "Tokenized Global Treasury Yield",
		description: "Tokenized government bond exposure from Brazil and Mexico.",
		category: "Macro",
		anchorSymbols: ["TESOURO", "CETES", "TLTx"],
		holdings: [
			{ symbol: "TESOURO", name: "TESOURO", weightBps: 5000 },
			{ symbol: "CETES", name: "CETES", weightBps: 5000 },
		],
	},
	{
		id: "indian-origin-ceo-basket",
		title: "Indian-Origin CEO Basket",
		description:
			"US companies led by Indian-origin chief executives across technology and consumer markets.",
		category: "People",
		anchorSymbols: ["ANETx", "MUx", "MAx"],
		historicalReturn1Y: 96.98,
		holdings: [
			{ symbol: "ANETx", name: "Arista Networks", weightBps: 1200 },
			{ symbol: "MUx", name: "Micron Technology", weightBps: 1100 },
			{ symbol: "MAx", name: "Mastercard", weightBps: 1100 },
			{ symbol: "GOOGLx", name: "Alphabet", weightBps: 1100 },
			{ symbol: "MSFTx", name: "Microsoft", weightBps: 1100 },
			{ symbol: "PANWx", name: "Palo Alto Networks", weightBps: 1100 },
			{ symbol: "ADBEx", name: "Adobe", weightBps: 1100 },
			{ symbol: "IBMx", name: "IBM", weightBps: 1100 },
			{ symbol: "PEPx", name: "PepsiCo", weightBps: 1100 },
		],
	},
	{
		id: "paypal-mafia",
		title: "PayPal Mafia",
		description:
			"Public companies founded, led or backed by members of the PayPal alumni network.",
		category: "People",
		anchorSymbols: ["TSLAx", "PLTRx", "METAx"],
		holdings: [
			{
				symbol: "TSLAx",
				name: "Tesla",
				weightBps: 1800,
				reason: "Elon Musk co-founded PayPal and leads Tesla.",
			},
			{
				symbol: "PLTRx",
				name: "Palantir",
				weightBps: 1400,
				reason: "Peter Thiel co-founded PayPal and chairs Palantir.",
			},
			{
				symbol: "METAx",
				name: "Meta",
				weightBps: 1200,
				reason: "Peter Thiel was Meta's first outside investor.",
			},
			{
				symbol: "MSFTx",
				name: "Microsoft",
				weightBps: 1200,
				reason:
					"Reid Hoffman founded LinkedIn and serves on Microsoft's board.",
			},
			{
				symbol: "GOOGLx",
				name: "Alphabet",
				weightBps: 1000,
				reason: "PayPal alumni founded YouTube, acquired by Google.",
			},
			{
				symbol: "ABNBx",
				name: "Airbnb",
				weightBps: 800,
				reason: "Reid Hoffman backed Airbnb through Greylock.",
			},
			{
				symbol: "XYZx",
				name: "Block",
				weightBps: 800,
				reason: "Keith Rabois was an early Block executive.",
			},
			{
				symbol: "OPENx",
				name: "Opendoor",
				weightBps: 600,
				reason: "Keith Rabois co-founded Opendoor.",
			},
			{
				symbol: "NFLXx",
				name: "Netflix",
				weightBps: 500,
				reason:
					"Former PayPal CFO Roelof Botha backed Netflix through Sequoia.",
			},
			{
				symbol: "PYPLx",
				name: "PayPal",
				weightBps: 400,
				reason: "The original company at the center of the network.",
			},
			{
				symbol: "COINx",
				name: "Coinbase",
				weightBps: 300,
				reason: "Peter Thiel's Founders Fund was an early backer.",
			},
		],
	},
	{
		id: "peptides-core",
		title: "Peptide Drug & Biotech",
		description:
			"Pharmaceutical and life-science companies involved in peptide drugs, research and production.",
		category: "Health",
		anchorSymbols: ["NVOx", "LLYx", "AZNx"],
		historicalReturn1Y: 2.84,
		holdings: [
			{
				symbol: "NVOx",
				name: "Novo Nordisk",
				weightBps: 2500,
				reason: "Develops Ozempic, Rybelsus and Wegovy.",
			},
			{
				symbol: "LLYx",
				name: "Eli Lilly",
				weightBps: 2500,
				reason: "Develops Mounjaro and other peptide therapies.",
			},
			{
				symbol: "AZNx",
				name: "AstraZeneca",
				weightBps: 1500,
				reason: "Expanding peptide drug research through partnerships.",
			},
			{ symbol: "ABBVx", name: "AbbVie", weightBps: 1000 },
			{ symbol: "MRKx", name: "Merck", weightBps: 1000 },
			{
				symbol: "TMOx",
				name: "Thermo Fisher Scientific",
				weightBps: 1000,
				reason: "Provides peptide synthesis and life-science infrastructure.",
			},
			{ symbol: "DHRx", name: "Danaher", weightBps: 500 },
		],
	},
	{
		id: "digital-dementia-fund",
		title: "AI Memory Chips & Semiconductors",
		description:
			"Memory-chip and compute companies supplying the infrastructure behind AI workloads.",
		category: "AI",
		anchorSymbols: ["MUx", "MRVLx", "AMDx"],
		historicalReturn1Y: 429.59,
		holdings: [
			{ symbol: "MUx", name: "Micron Technology", weightBps: 5000 },
			{ symbol: "MRVLx", name: "Marvell Technology", weightBps: 1800 },
			{ symbol: "AMDx", name: "AMD", weightBps: 1600 },
			{ symbol: "ARMx", name: "Arm Holdings", weightBps: 1600 },
		],
	},
	{
		id: "ozempic-glp-1",
		title: "Ozempic / GLP-1",
		description:
			"Leading GLP-1 drug producers and obesity-treatment challengers.",
		category: "Health",
		anchorSymbols: ["LLYx", "NVOx", "AMGNx"],
		holdings: [
			{
				symbol: "LLYx",
				name: "Eli Lilly",
				weightBps: 3580,
				reason: "Produces tirzepatide-based GLP-1 treatments.",
			},
			{
				symbol: "NVOx",
				name: "Novo Nordisk",
				weightBps: 3580,
				reason: "Produces semaglutide therapies including Ozempic and Wegovy.",
			},
			{
				symbol: "AMGNx",
				name: "Amgen",
				weightBps: 2840,
				reason: "Develops maridebart cafraglutide as a GLP-1 candidate.",
			},
		],
	},
	{
		id: "made-in-america",
		title: "US Manufacturing & Reshoring",
		description:
			"Domestic semiconductors, critical materials and hardware benefiting from US reshoring.",
		category: "Industry",
		anchorSymbols: ["COPXx", "MUx", "DELLx"],
		holdings: [
			{ symbol: "USDC", name: "Cash", weightBps: 1390 },
			{ symbol: "COPXx", name: "Copper miners", weightBps: 2680 },
			{ symbol: "MUx", name: "Micron Technology", weightBps: 2630 },
			{ symbol: "DELLx", name: "Dell Technologies", weightBps: 1770 },
			{ symbol: "USARx", name: "USA Rare Earth", weightBps: 1080 },
			{ symbol: "INTCx", name: "Intel", weightBps: 450 },
		],
	},
	{
		id: "ansem-alpha",
		title: "Ansem Alpha",
		description:
			"A crypto basket following the highest-conviction public calls from trader Ansem.",
		category: "Crypto",
		anchorSymbols: ["SOL", "BTC", "PUMP"],
		holdings: [
			{ symbol: "USDC", name: "Cash", weightBps: 4330 },
			{ symbol: "SOL", name: "Solana", weightBps: 2520 },
			{ symbol: "BTC", name: "Bitcoin", weightBps: 1150 },
			{ symbol: "PUMP", name: "Pump.fun", weightBps: 1010 },
			{ symbol: "HYPE", name: "Hyperliquid", weightBps: 500 },
			{ symbol: "ETH", name: "Ethereum", weightBps: 490 },
		],
	},
	{
		id: "a16z-index",
		title: "The a16z Index",
		description:
			"Public-market proxies for a16z themes across AI compute, crypto and American Dynamism.",
		category: "Tech",
		anchorSymbols: ["NVDAx", "COINx", "SPACEX"],
		holdings: [
			{ symbol: "USDC", name: "Cash", weightBps: 1932 },
			{ symbol: "NVDAx", name: "NVIDIA", weightBps: 1076 },
			{ symbol: "COINx", name: "Coinbase", weightBps: 896 },
			{ symbol: "CRWVx", name: "CoreWeave", weightBps: 717 },
			{ symbol: "SPACEX", name: "SpaceX", weightBps: 717 },
			{ symbol: "SOL", name: "Solana", weightBps: 717 },
			{ symbol: "CRCLx", name: "Circle", weightBps: 538 },
			{ symbol: "ETH", name: "Ethereum", weightBps: 538 },
			{ symbol: "HOODx", name: "Robinhood", weightBps: 448 },
			{ symbol: "PLTRx", name: "Palantir", weightBps: 448 },
			{ symbol: "RKLBx", name: "Rocket Lab", weightBps: 359 },
			{ symbol: "UNI", name: "Uniswap", weightBps: 359 },
			{ symbol: "NBISx", name: "Nebius", weightBps: 359 },
			{ symbol: "SUI", name: "Sui", weightBps: 269 },
			{ symbol: "OP", name: "Optimism", weightBps: 269 },
			{ symbol: "WLD", name: "Worldcoin", weightBps: 179 },
			{ symbol: "EIGEN", name: "EigenLayer", weightBps: 179 },
		],
	},
	{
		id: "hormuz-index",
		title: "Oil & Gold During Hormuz Risk",
		description:
			"Oil, gold and energy exposure positioned for disruption around the Strait of Hormuz.",
		category: "Macro",
		anchorSymbols: ["XLEx", "GLDx", "XOMx"],
		holdings: [
			{ symbol: "USDC", name: "Cash", weightBps: 1500 },
			{ symbol: "WTI", name: "Crude Oil WTI", weightBps: 3120 },
			{ symbol: "BRENT", name: "Brent Oil", weightBps: 2910 },
			{ symbol: "GLDx", name: "Gold", weightBps: 2260 },
			{
				symbol: "XLEx",
				name: "Energy Select Sector SPDR Fund",
				weightBps: 210,
			},
		],
	},
	{
		id: "humanoids",
		title: "Humanoid Robotics",
		description:
			"Robot makers and compute suppliers building the emerging humanoid workforce.",
		category: "Industry",
		anchorSymbols: ["TSLAx", "NVDAx", "BOTx"],
		holdings: [
			{ symbol: "UNITREE", name: "Unitree", weightBps: 3790 },
			{ symbol: "TSLAx", name: "Tesla", weightBps: 2100 },
			{ symbol: "NVDAx", name: "NVIDIA", weightBps: 1850 },
			{ symbol: "HYUNDAI", name: "Hyundai", weightBps: 1420 },
			{ symbol: "BOTx", name: "RoboStrategy", weightBps: 840 },
		],
	},
];
